### ISSUE TITLE
Fails to discover tests in a DLL with CATCH_CONFIG_RUNNER defined

### ISSUE THREAD

**Issue by ScottEllisNovatex** [xkbeyer/CatchTestAdapter#13]
I have been using colonelsammy's version of catch within VS 2017, and it does a good job. However it is not being maintained so would like to change to using the current catch2 with your adapter.

I am mainly working on a windows dll at the moment, and it has been very useful to have a file of tests included in the build of the dll, and then run the tests in the dll with the test explorer without having to switch to another project.

I have tried this with CatchTestAdaptor with CATCH_CONFIG_RUNNER defined and an exported method to call Catch::Session().run(argc, argv); but the tests are not being discovered. If I do this with a normal exe it works ok. 

Is this a limitation of how the VS test explorer works (colonelsammy's version working in this way would seem to indicate not) or how CatchTestAdaptor "finds" the tests?

**Comment by xkbeyer** [comment]
The test adapter is only called by VS Test if the project target is an EXE. The test adapter registers this accordingly. The discover process is based on the fact that the EXE is called and returns the test cases, and so on. If and how this works with a DLL I don't know at the moment.

**Comment by xkbeyer** [comment]
I looked into what colonelsammy made. He changed Catch itself to use the `VsiualStudio::CppUnitTestFramework`. That is a complete different approach and not comparable with what a TestAdapter is.
