### ISSUE TITLE
if a test executable throws during execution, it's removed from Test Explorer

### ISSUE THREAD

**Issue by vvuk** [xkbeyer/CatchTestAdapter#16]
I've got a test executable that's hitting a runtime assert during one of the tests.  When run through Test Explorer via "Run All", all the tests are discovered:

```
[7/19/2018 5:19:25 PM Informational] Catch Discover in process ...
[7/19/2018 5:19:25 PM Informational] Inclusion patterns: build\\win64\\Debug\\.*Test\.exe
[7/19/2018 5:19:25 PM Informational] Processing catch test source: 'C:\build\win64\Debug\ArchTest.exe'...
[7/19/2018 5:19:25 PM Informational] Test 1
[7/19/2018 5:19:25 PM Informational] Test 2
[7/19/2018 5:19:25 PM Informational] ...
```
and at that point, they show up in Test Explorer with a clock icon next to them.  But when the test executable is run, it pops up an assertion failed dialog (just regular C++ `assert`), and this:

```
[7/19/2018 5:19:26 PM Informational] CatchAdapter::RunTests... 
[7/19/2018 5:19:26 PM Informational] RunTest with source C:\build\win64\Debug\ArchTest.exe
[7/19/2018 5:19:34 PM Informational] Overall time 00:00:08.1492876
[7/19/2018 5:19:34 PM Error] Exception running tests: There is an error in XML document (1, 1743).
[7/19/2018 5:19:34 PM Error] Exception stack:    at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(Stream stream)
   at CatchTestAdapter.TestExecutor.RunTests(IEnumerable`1 tests, IRunContext runContext, IFrameworkHandle frameworkHandle)
   at CatchTestAdapter.TestExecutor.RunTests(IEnumerable`1 sources, IRunContext runContext, IFrameworkHandle frameworkHandle)
```

At the end of the run (after all the test executables are run), the test entry for the ArchTest executable disappears entirely from Test Explorer.

**Comment by xkbeyer** [comment]
I see the problem. The assert stops the process and then the output is not complete, therefor the XML exception. Currently I don't see a way to handle it. However, why using an assert in a TEST? Why not the CHECK/REQUIRE etc macros? IMHO an assert in a TEST_CASE makes no sense.

**Comment by vvuk** [comment]
The assert isn't in the test itself -- a test was triggering an internal code invariant, and we assert/abort there.  I think all that's needed would be to wrap the deserialization in a try/catch and not let the exception propagate upwards, which I think is what causes the test explorer to remove the test entirely.  That should leave the tests in a ? state.  I'll give that a try later today and see if it fixes things.

**Comment by vvuk** [comment]
Yep, this fixes things up.  The test is left in a <!> state (meaning I can go and fix the assert and rerun, or debug :)

**Comment by xkbeyer** [comment]
Really? I get an other result. The TestExplorer doesn't show any tests. May be my set up is different.
I did the follwing test:
```
int function_with_assert()
{
   assert(false);
   return 5;
}

TEST_CASE("C++ assert")
{
   REQUIRE(function_with_assert() == 5);
}
```
Any Idea?

**Comment by vvuk** [comment]
Hmm.  Let me try that specifically.  Is there a way to debug/test the test adapter, without having to go through the installation step every time?  I'd like to try that out in the reference project but having to install/uninstall is painful

**Comment by vvuk** [comment]
Ok, I can reproduce that and I understand what's going on.  When it was succeeding for me, I was cancelling the run halfway through the test suites, which left the test in the <!> state.  If I let the run fully complete, the test disappears, presumably because the test runner never sent any results back.  Going to try to generate dummy results.

I've fixed it with an update to PR #17 -- now instead of parsing the XML doc result all in one go, it's parsed one testcase at a time.  In case of failure to parse, all remaining test cases are emitted with None status, making the test runner/test explorer happy.

**Comment by xkbeyer** [comment]
Regarding Debugging:
There is no need to install it. You can start the project with F5. Then an experimental VS instance is started in which the extension is already installed. The problem here is that breakpoints do not work (because the adapter runs in another process). Here I help by setting `System.Diagnostics.Debugger.Launch()` instead of a breakpoint. That's not nice but I haven't found another way yet.

**Comment by vvuk** [comment]
For debugging, I ended up following this -- https://stackoverflow.com/questions/43712659/how-do-i-debug-a-custom-test-adapter-in-visual-studio and it (mostly) worked.  Faster than a full VS instance spawn.  I still had to `Debugger.Launch()`, though I got it to work one time without it; I think I didn't have the child debugging configured 100% correctly.

**Comment by xkbeyer** [comment]
Thanks for the links, it helps. For me the breakpoints works too. I enabled native code debugging to have them and I have to set `<all other processes>` to `Attach to debugger`. I tried the filter but w/o success.

**Comment by xkbeyer** [comment]
I'll close the issue, since I merged the PR.
