### ISSUE TITLE
Show sections as distinct tests, ideally with hierarchy

### ISSUE THREAD

**Issue by vvuk** [xkbeyer/CatchTestAdapter#18]
Hierarchy doesn't seem to be a strong part of the Test Explorer in VS, but it would be nice to (optionally, via config?) break out test cases with sections into their own entries in the explorer.  That is:

```
TEST_CASE("Foo") {
    int x = 42;
    SECTION("less than") {
        REQUIRE(x < 100);
    }
    SECTION("equals") {
        REQUIRE(x == 42);
    }
}
```

could show up as "Foo", "Foo -- less than" and "Foo -- equals", rather than just Foo.

The main issue with this is that sections can only be discovered while running, but the framework already supports dynamic (at runtime) test discovery.

A second, minor, issue is that for the runner, only one section name can be specified via `-c`; this means that complex test cases with nested sections such as:

```
TEST_CASE("Foo") {
    SECTION("less than") {
        SECTION("something else") {
            ...;
        }
    }
}
```

won't be directly runnable, but that's more a limit of Catch itself.

**Comment by xkbeyer** [comment]
Yes, it would be nice with `SCENARIO`, too. 
If and how confusing it is when something else can be seen in the discover phase than after a test run, I don't know yet. But I think it makes a lot of sense to switch via Config. I think, but then a single `SECTION` must also be able to be executed otherwise it doesn't make sense. It also means quite a change. I think I'll give it a try.

**Comment by xkbeyer** [comment]
One approach would be to have one test case with multiple test results.
Taken the example (slightly changed to generate failures):
```cpp
TEST_CASE("Foo")
{
   int x = 42;
   SECTION("less than")
   {
      x *= 4;
      REQUIRE(x < 100);
   }
   SECTION("equals")
   {
      ++x;
      REQUIRE(x == 42);
   }
}
```
The current TestExplorer would display:
![testexplorer_now](https://user-images.githubusercontent.com/10296657/43367617-31191afa-9350-11e8-9241-32c5815d7bd6.PNG)

Same but one test case with multiple results:
![testexplorer_then](https://user-images.githubusercontent.com/10296657/43367626-5336f292-9350-11e8-9bb4-a2281ab2a16f.PNG)

I think, It is better than now, but I'll try the approach to generate new test cases while running, too.

**Comment by vvuk** [comment]
Having multiple results would be better than now, but I think generating new dynamic test cases would be the best so that you actually see the success results as well.  I suspect if you store on the `TestCase` a generated name that includes the section, but store the test name and the section separately in `LocalExtensionData` or similar, you can pull it out during execution (and then pass via `-c` to select the section).

I wish we could specify a real hierarchy in the test explorer, but that doesn't seem to be supported.. maybe one day.

**Comment by xkbeyer** [comment]
Currently I have a version which shows a hierarchy after the `TestExecutor` run.
![hierarchy](https://user-images.githubusercontent.com/10296657/43414255-8e9a15d4-9432-11e8-9465-b39252547dda.PNG)
But Catch2 seems not to support the -c for `SCENARIO`.
Yes, I have to store the information about the sections names somewhere. The first idea was to use the `FullyQualifiedName` to store it. But if that doesn't work I try the `LocalExtensionData`

**Comment by vvuk** [comment]
Hey that looks great!  If I look at the catch source, scenarios etc. are mapped to test cases and sections with generated names:

```
#define CATCH_SCENARIO( ... ) CATCH_TEST_CASE( "Scenario: " __VA_ARGS__ )
#define CATCH_SCENARIO_METHOD( className, ... ) INTERNAL_CATCH_TEST_CASE_METHOD( className, "Scenario: " __VA_ARGS__ )
#define CATCH_GIVEN( desc )    CATCH_SECTION( std::string( "Given: ") + desc )
#define CATCH_WHEN( desc )     CATCH_SECTION( std::string( " When: ") + desc )
#define CATCH_AND_WHEN( desc ) CATCH_SECTION( std::string( "  And: ") + desc )
#define CATCH_THEN( desc )     CATCH_SECTION( std::string( " Then: ") + desc )
#define CATCH_AND_THEN( desc ) CATCH_SECTION( std::string( "  And: ") + desc )
```
So `-c` should work, but with `"Given: <the string>"` or `"  And: <something else>"`.  I think that BDD-style isn't treated any differently in the reporters, so it should "just work" if you auto discover sections via the results.. you should see the `"  And: <...>"` as section names.  (I haven't confirmed this in reality though :)

**Comment by xkbeyer** [comment]
What I did't try was to put enough spaces in front. So if I add 3 spaces to `Given` and 4 to `When` then it works.

**Comment by xkbeyer** [comment]
Finally I have a working version [pre release v1.5.0](https://github.com/xkbeyer/CatchTestAdapter/tree/v1.5.0).
Give it a try and let me know of any issues.
There is a way to get a deeper hierarchy but until now I don't get the desired results...

**Comment by smkanadl** [comment]
The 1.5 pre-release is working fine for me, just as I expected things to work. Good work!

**Comment by vvuk** [comment]
Apologies for the really slow feedback -- this is working great!

**Comment by xkbeyer** [comment]
@vvuk No problem.

Thanks for the feedback.
