### ISSUE TITLE
Support Visual Studio 2019

### ISSUE THREAD

**Issue by smkanadl** [xkbeyer/CatchTestAdapter#20]
As the release of the next Visual Studio version is quite soon, I would like to ask if you already have plans for an updated version of the Test Adapter.

**Comment by xkbeyer** [comment]
Yes, as soon as VS2019 is released and available,

**Comment by xkbeyer** [comment]
Release Version 1.5.1 does support Visual Studio 2019.
Please give it a try.

**Comment by smkanadl** [comment]
Thanks a lot. Works at least for me :-)

**Comment by xkbeyer** [comment]
My pleasure:)
